"""add_descriptions_columns_qa_analises

Revision ID: 4861830de0a6
Revises: b7c7f040254b
Create Date: 2026-02-03 04:28:49.418624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4861830de0a6'
down_revision: Union[str, Sequence[str], None] = 'b7c7f040254b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_analyses', sa.Column('tests_description', sa.Text(), nullable=True))
    op.add_column('qa_analyses', sa.Column('playwright_description', sa.Text(), nullable=True))
    op.add_column('qa_analyses', sa.Column('documentation_description', sa.Text(), nullable=True))
    op.add_column('qa_analyses', sa.Column('uiux_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_analyses', 'uiux_description')
    op.drop_column('qa_analyses', 'documentation_description')
    op.drop_column('qa_analyses', 'playwright_description')
    op.drop_column('qa_analyses', 'tests_description')
    # ### end Alembic commands ###
