"""add_deleted_at_column_test_case_steps

Revision ID: 6c2a92e9283d
Revises: 4861830de0a6
Create Date: 2026-02-04 01:02:02.911163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2a92e9283d'
down_revision: Union[str, Sequence[str], None] = '4861830de0a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case_steps', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case_steps', 'deleted_at')
    # ### end Alembic commands ###
