"""create_playwright_scripts_table

Revision ID: 86ef44098b2b
Revises: df86610936e9
Create Date: 2026-02-04 06:02:53.601922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ef44098b2b'
down_revision: Union[str, Sequence[str], None] = 'df86610936e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playwright_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('generator_model', sa.String(length=100), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['qa_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'version', name='uq_playwright_scripts_analysis_version')
    )
    op.create_index(op.f('ix_playwright_scripts_analysis_id'), 'playwright_scripts', ['analysis_id'], unique=False)
    op.create_index('ix_playwright_scripts_analysis_status', 'playwright_scripts', ['analysis_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_playwright_scripts_analysis_status', table_name='playwright_scripts')
    op.drop_index(op.f('ix_playwright_scripts_analysis_id'), table_name='playwright_scripts')
    op.drop_table('playwright_scripts')
    # ### end Alembic commands ###
