"""create_test_case_table

Revision ID: 97d74aeb9e1e
Revises: b77b56c45a47
Create Date: 2025-12-17 03:18:59.796797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d74aeb9e1e'
down_revision: Union[str, Sequence[str], None] = 'b77b56c45a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qa_analysis_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('test_type', sa.Enum('functional', 'regression', 'smoke', 'exploratory', name='test_type_enum'), nullable=False),
    sa.Column('scenario_type', sa.Enum('positive', 'negative', 'edge', name='scenario_type_enum'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='test_priority_enum'), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='test_risk_enum'), nullable=False),
    sa.Column('preconditions', sa.Text(), nullable=True),
    sa.Column('postconditions', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('generated', 'reviewed', 'approved', 'deprecated', name='test_case_status_enum'), nullable=False),
    sa.Column('has_automation', sa.Boolean(), nullable=False),
    sa.Column('automation_status', sa.Enum('not_generated', 'generated', 'outdated', name='automation_status_enum'), nullable=False),
    sa.Column('generated_by_ai', sa.Boolean(), nullable=False),
    sa.Column('ai_model_used', sa.String(length=100), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['qa_analysis_id'], ['qa_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_qa_analysis_id'), 'test_cases', ['qa_analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_cases_qa_analysis_id'), table_name='test_cases')
    op.drop_table('test_cases')
    # ### end Alembic commands ###
