"""add_screen_context_column

Revision ID: b77b56c45a47
Revises: e09e18d5f85c
Create Date: 2025-12-17 02:55:05.852722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b77b56c45a47'
down_revision: Union[str, Sequence[str], None] = 'e09e18d5f85c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_analyses', sa.Column('screen_context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_analyses', 'screen_context')
    # ### end Alembic commands ###
