"""create_documentations_table

Revision ID: ba6870b9bf68
Revises: 86ef44098b2b
Create Date: 2026-02-09 00:50:14.496737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba6870b9bf68'
down_revision: Union[str, Sequence[str], None] = '86ef44098b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qa_analysis_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_format', sa.String(length=50), nullable=False),
    sa.Column('generated_by', sa.String(length=50), nullable=False),
    sa.Column('generator_model', sa.String(length=100), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['qa_analysis_id'], ['qa_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qa_analysis_id', 'version', name='uq_documentations_analysis_version')
    )
    op.create_index('ix_documentations_analysis_status', 'documentations', ['qa_analysis_id', 'status'], unique=False)
    op.create_index(op.f('ix_documentations_qa_analysis_id'), 'documentations', ['qa_analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documentations_qa_analysis_id'), table_name='documentations')
    op.drop_index('ix_documentations_analysis_status', table_name='documentations')
    op.drop_table('documentations')
    # ### end Alembic commands ###
