"""mudadncas_access_credentials

Revision ID: c97a63f56521
Revises: 2603b9df6ff0
Create Date: 2026-04-03 05:32:35.250733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c97a63f56521'
down_revision: Union[str, Sequence[str], None] = '2603b9df6ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_credentials', sa.Column('screen_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('fk_access_credentials_target_id'), 'access_credentials', type_='foreignkey')
    op.create_foreign_key(None, 'access_credentials', 'screens', ['screen_id'], ['id'], ondelete='CASCADE')
    op.drop_column('access_credentials', 'target_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_credentials', sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'access_credentials', type_='foreignkey')
    op.create_foreign_key(op.f('fk_access_credentials_target_id'), 'access_credentials', 'targets', ['target_id'], ['id'], ondelete='CASCADE')
    op.drop_column('access_credentials', 'screen_id')
    # ### end Alembic commands ###
