"""add_deleted_at_column_test_cases

Revision ID: df86610936e9
Revises: fb05c2e7593c
Create Date: 2026-02-04 01:07:32.155256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df86610936e9'
down_revision: Union[str, Sequence[str], None] = 'fb05c2e7593c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_cases', 'deleted_at')
    # ### end Alembic commands ###
