"""add_enum_option_test_cases

Revision ID: fb05c2e7593c
Revises: 6c2a92e9283d
Create Date: 2026-02-04 01:03:48.583144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb05c2e7593c'
down_revision: Union[str, Sequence[str], None] = '6c2a92e9283d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
